config/routes.rb
MyA2p::Application.routes.draw do
  resources :groups

  resources :pupils do
    collection { post :import }
  end
  
  root 'pupils#index'

  # The priority i based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/pupil.rb
# A2p Pupil class definition
class Pupil < ActiveRecord::Base
  has_many :pupil_groups, dependent: :destroy
  has_many :groups, through: :pupil_groups
  
  validates :given_name, presence: true
  validates :family_name, presence: true
  #validates :image_path, allow_blank: true, url: true
  # So far I can't figure out how to check the url is well formed and
  # actually points to the image file. TODO!
  validates :image_path, allow_blank: true, format: {
    with: /\.(gif|jpg|png)\z/i,
    message: 'URL must point to GIF/JPG/PNG file'
  }

  # Define an importer for pupil data from csv or excel files.
  # Does not handle updating existing files yet.
  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      pupil_hash = Hash[[header, spreadsheet.row(i)].transpose]
      pupil = Pupil.where(id: pupil_hash['id'])
      pupil.count == 1 ? pupil.first.update_attributes(pupil_hash) :
                         Pupil.create!(pupil_hash)
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::CSV.new(file.path)
    when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
    when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
    else fail "Unknown file type: #{file.original_filename}"
    end
  end
  
  #def self.add_image()
  #end

  def name
    [given_name, family_name].join ' '
  end
end

app/controllers/pupils_controller.rb
# Pupil controller
class PupilsController < ApplicationController
  before_action :set_pupil, only: [:show, :edit, :update, :destroy]

  # GET /pupils
  # GET /pupils.json
  def index
    @pupils = Pupil.all
  end

  # GET /pupils/1
  # GET /pupils/1.json
  def show
    @pupil_groups = @pupil.groups
  end

  # GET /pupils/new
  def new
    @pupil = Pupil.new
    @group_list = set_group_list
  end

  # GET /pupils/1/edit
  def edit
    @group_selected = Array.new
    @pupil.groups.each do |g|
      @group_selected.push(g.id)
    end
    @group_list = set_group_list
  end

  # POST /pupils
  # POST /pupils.json
  def create
    if (params[:pupil].has_key?(:image_path)) then
      params[:pupil][:image_path] = set_image
    end
    @pupil = Pupil.new(pupil_params)
    clean_select_multiple_params params[:groups]
    @pupil_groups = Group.find(params[:groups][:id])
    @pupil.groups = @pupil_groups
    logger.debug "The groups parameter contains: #{params[:groups][:id]}"
    logger.debug "The groups retrieved are: #{@pupil_groups}"
    respond_to do |format|
      if @pupil.save
        format.html { redirect_to @pupil, notice: 'Pupil was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pupil }
      else
        format.html { render action: 'new' }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pupils/1
  # PATCH/PUT /pupils/1.json
  def update
    respond_to do |format|
      clean_select_multiple_params params[:groups]
      @pupil_groups = Group.find(params[:groups][:id])
      @pupil.groups = @pupil_groups
      if (params[:pupil].has_key?(:image_path)) then
        params[:pupil][:image_path] = set_image
      end
      if @pupil.update(pupil_params)
        format.html { redirect_to @pupil, notice: 'Pupil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pupils/1
  # DELETE /pupils/1.json
  def destroy
    @pupil.destroy
    respond_to do |format|
      format.html { redirect_to pupils_url }
      format.json { head :no_content }
    end
  end

  def import
    Pupil.import(params[:file])
    redirect_to root_url, notice: 'Pupils imported.'
  rescue
    redirect_to root_url, notice: 'Invalid file format.'
  end # end def import.

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pupil
    @pupil = Pupil.find(params[:id])
  end
  
  def set_image
    rails_root = Rails.root
    uploaded_io = params[:pupil][:image_path]
    image_pathname = rails_root.join('public',
                                     'uploads',
                                     uploaded_io.original_filename)
    File.open(image_pathname, 'wb') do |file|
      file.write(uploaded_io.read)
    end
    img_addr = image_pathname.to_s.tap { |s| s.slice!(rails_root.to_s) }
    logger.debug " Image path with slice: #{img_addr.inspect}"
    return img_addr
  end

def set_group_list
  return Group.all
end

def clean_select_multiple_params hash = params
  hash.each do |k, v|
    case v
    when Array then v.reject!(&:blank?)
    when Hash then clean_select_multiple_params(v)
    end
  end
end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def pupil_params
    params.require(:pupil).permit(:given_name, :other_name, :family_name,
                                  :name_known_by, :dob, :gender, :image_path)
  end
end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/views/pupils/_form.html.erb
<%= form_for(@pupil) do |f| %>
  <% if @pupil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pupil.errors.count, "error") %> prohibited this pupil from being saved:</h2>

      <ul>
      <% @pupil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name %>
  </div>
 <!-- <div class="field">
    <%= f.label :other_name %><br>
    <%= f.text_field :other_name %>
  </div>-->
  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>
  <!--<div class="field">
    <%= f.label :name_known_by %><br>
    <%= f.text_field :name_known_by %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.number_field :gender %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.file_field :image_path %>
  </div>-->
  <div class="field">
    <%= f.label 'Pupil Groups' %><br>
    <%= collection_select(:groups, :id, @group_list,
                          :id, :name,
                          (defined?(@group_selected)).nil? ? { } :
                                                { :selected => @group_selected },
                          { :multiple => true }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pupils/edit.html.erb
<h1>Editing pupil</h1>

<%= render 'form' %>

<%= link_to 'Show', @pupil %> |
<%= link_to 'Back', pupils_path %>

app/views/pupils/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A2P | Pupils</title>
  </head>

<h1>Listing pupils</h1>

<%= flash[:notice] %>

<table>
  <thead>
    <tr>
      <th>Given name</th>
      <th>Other name</th>
      <th>Family name</th>
      <th>Name known by</th>
      <th>Dob</th>
      <th>Gender</th>
      <th>Image path</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pupils.each do |pupil| %>
      <tr>
        <td><%= pupil.given_name %></td>
        <td><%= pupil.other_name %></td>
        <td><%= pupil.family_name %></td>
        <td><%= pupil.name_known_by %></td>
        <td><%= pupil.dob %></td>
        <td><%= pupil.gender %></td>
        <td><%= pupil.image_path %></td>
        <td><%= link_to 'Show', pupil %></td>
        <td><%= link_to 'Edit', edit_pupil_path(pupil) %></td>
        <td><%= link_to 'Destroy', pupil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
<h3>Import Pupils</h3>
  <%= form_tag import_pupils_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</div>


<br>

<%= link_to 'New Pupil', new_pupil_path %>

app/views/pupils/new.html.erb
<h1>New pupil</h1>

<%= render 'form' %>

<%= link_to 'Back', pupils_path %>

app/views/pupils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @pupil.given_name %>
</p>

<p>
  <strong>Other name:</strong>
  <%= @pupil.other_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @pupil.family_name %>
</p>

<p>
  <strong>Name known by:</strong>
  <%= @pupil.name_known_by %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @pupil.dob %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @pupil.gender %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @pupil.image_path %>
</p>

<p><strong>Groups</strong><br>
<% @pupil_groups.each do |pg| %>
  <div>
    <%= pg.name %> <br>
  </div>
<% end %>
</p>

<%= link_to 'Edit', edit_pupil_path(@pupil) %> |
<%= link_to 'Back', pupils_path %>